version: '3.3'
services:
  rabbitmq:
    image: rabbitmq:3-management
    build:
      context: ./Dockers
      dockerfile: RabbitMQ.Dockerfile 
    ports:
    - "5672:5672"
    - "15672:15672"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:15672"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks: 
      - def-network

  authapi:
    image: evreich/javaauth:${TAG:-latest}
    build:
      context: ./AlphaParking.Java.AuthService/javaauth
      dockerfile: Dockerfile   
    ports:
    - "8181:8181" 
    environment:
    - EVENTBUS_HOST=rabbitmq
    - EVENTBUS_PORT=5672
    - SERVER_PORT=8181
    links: 
    - rabbitmq
    depends_on:
    - rabbitmq
    networks: 
      - def-network

  parkingapi:
    image: evreich/alphaparking:${TAG:-latest}
    build:
      context: ./AlphaParking
      dockerfile: Web.Host.Dockerfile   
    ports:
    - "8182:8182"
    environment:
    - EVENTBUS_HOST=rabbitmq
    - EVENTBUS_PORT=5672
    - ASPNETCORE_URLS=http://*:8182
    restart: on-failure
    depends_on:
    - rabbitmq
    links: 
    - rabbitmq
    # command: dockerize -wait tcp://rabbitmq:15672 -wait tcp://rabbitmq:5672
    networks: 
      - def-network

  gatewayapi:
    image: evreich/gateway:${TAG:-latest}
    build:
      context: ./AlphaParking/AlphaParking.Web.Gateway
      dockerfile: Dockerfile
    ports:
    - "9000:9000"
    environment:
    - ASPNETCORE_ENVIRONMENT=prod
    - ASPNETCORE_URLS=http://*:9000
    networks: 
      - def-network

  webmvc:
    image: evreich/javaclient:${TAG:-latest}
    build:
      context: ./AlphaParking.Java.Client/javaclient
      dockerfile: Dockerfile  
    ports:
    - "8585:8585"  
    environment:
    - GATEWAY_HOST=gatewayapi
    - GATEWAY_PORT=9000
    - SERVER_PORT=8585
    depends_on:
    - gatewayapi
    links: 
    - gatewayapi
    networks: 
      - def-network

  webspa:
    image: evreich/client:${TAG:-latest}
    build:
      context: ./AlphaParking/AlphaParking.Web.Client
      dockerfile: Dockerfile  
    ports:
    - "8383:8383"  
    environment:
    - GATEWAY_HOST=gatewayapi
    - GATEWAY_PORT=9000
    - ASPNETCORE_URLS=http://*:8383
    depends_on:
    - gatewayapi
    links: 
    - gatewayapi
    networks: 
      - def-network

networks:
  def-network:
    